### PR TITLE
 added support to generate code for https://pub.dev/packages/json_serializable. 

### PR DESCRIPTION
**Pull request by sagarmahobia**
Added a check box and functionality to generate code for @JsonSerializable. Check and merge if you find it useful. Thank You.

### CODE REVIEW

**Comment by sagarmahobia** [comment]
check output_serialization.dart for code format.

**Comment by sagarmahobia** [comment]
todo  <label for="use-serializable"... . missed to change.

**Comment by chunlee-thong** [comment]
I have never use package json_serializable myself and since we don't have any test in this package, please do some manually test as much as possible.

**Comment by chunlee-thong** [comment]
https://github.com/sagarmahobia/dart-quicktype/blob/3239fe7e0ac5d13172d2df53c17351169f08afa6/src/custom_dart_renderer.ts#L557
I found a bug where you always add @JsonKey annotation even i don't use JsonSerializable

**Comment by sagarmahobia** [comment]
> https://github.com/sagarmahobia/dart-quicktype/blob/3239fe7e0ac5d13172d2df53c17351169f08afa6/src/custom_dart_renderer.ts#L557 I found a bug where you always add @jsonkey annotation even I don't use JsonSerializable

json:
        "backdrop_path" : "some/string"

dart:
@JsonKey(name: 'backdrop_path') 
final String? backdropPath;

It binds the JSON key that is backdrop_path  to variable to backdropPath variable. it is emitting lines correctly. As I can see.

equivalent to backdropPath : json["backdrop_path" is the dart constructor.

Screenshot 2022-06-28 at 10 38 13 AM


You can see in the image I've been using this in my projects without any issue.

**Comment by sagarmahobia** [comment]
> https://github.com/sagarmahobia/dart-quicktype/blob/3239fe7e0ac5d13172d2df53c17351169f08afa6/src/custom_dart_renderer.ts#L557 I found a bug where you always add @jsonkey annotation even i don't use JsonSerializable

tried to solve it. check once.

**Comment by sagarmahobia** [comment]
> > https://github.com/sagarmahobia/dart-quicktype/blob/3239fe7e0ac5d13172d2df53c17351169f08afa6/src/custom_dart_renderer.ts#L557 I found a bug where you always add @jsonkey annotation even i don't use JsonSerializable
> 
> tried to solve it. check once.

https://github.com/chunlee-thong/dart-quicktype/blob/47569584e627a08e467b229a009caf8ae40e8842/src/custom_dart_renderer.ts#L559

**Comment by chunlee-thong** [comment]
Ran few testing, LGTM.

**Pull request merged**
